---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# zonebuilder

<!-- badges: start -->
<!-- badges: end -->

The goal of zonebuilder is to ...

## Installation

You can install the released version of zonebuilder from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("zonebuilder")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("robinlovelace/zonebuilder")
```

## Example

```{r}
library(sf)
devtools::load_all()
plot(zb_region)
```

The aim is to be able to break up geographical space into discrete chunks.
The syntax is designed to be user friendly, e.g.:

```{r}
x = zb_region
q = zb_quadrat(x, 4) # break into 4
plot(q)
```

Or doughnuts

```{r}
plot(zb_doughnut(x, n = 4))
doughnut_4km = zb_doughnut(x, d = 4)
doughnut_4km
plot(sf::st_geometry(doughnut_4km))
plot(doughnut_4km[3, ], col = "blue", add = TRUE)
```



